Repository MaeumGaGym/MaeumGaGym_Backend, pull requests merged in 2023-12, with the labels that each got.

#5 🔀 :: GetAccessToken 삭제
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/GetKakaoAccessTokenUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/GetKakaoAccessTokenPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/GetKakaoAccessTokenService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/adapter/KakaoAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/feign/oauth/kakao/KakaoAuthClient.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/scan/PropertiesScanConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/env/kakao/KakaoProperties.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/auth/controller/KakaoAuthController.kt
Labels: enhancement

#9 🔀 :: gi501476/ma-49-apple-oauth to develop
  maeumgagym-core/build.gradle.kts
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/dto/response/ApplePublicKey.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/dto/response/ApplePublicKeys.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/AppleLoginUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/AppleJwtParsePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/GenerateJwtPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/GeneratePublicKeyPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/JwtExpiredCheckPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/ParsePublicKeyPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/ReadApplePublicKeyPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/AppleLoginService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/adapter/AppleAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/adapter/GeneratePublicKeyAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/feign/oauth/apple/AppleClient.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/AppleJwtParser.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtFilter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtResolver.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/FilterConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/SecurityConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/jwt/JwtFilter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/token/JwtAdapter.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/auth/controller/AppleAuthController.kt
Labels: enhancement

#14 🔀 :: 회원탈퇴 API 개발
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/UserPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/entity/UserJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/mapper/UserMapper.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/WithdrawalUserUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/ReadCurrentUserPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/AppleLoginService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/GoogleLoginService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoLoginService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/WithdrawalUserService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/model/User.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/DeleteUserPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/FindUserByUUIDPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/SaveUserPort.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtFilter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/FilterConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/SecurityConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/principle/CustomUserDetailService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/principle/CustomUserDetails.kt
  maeumgagym-infrastructure/src/main/resources/application.yml
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/auth/controller/AuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/auth/controller/KakaoAuthController.kt
Labels: enhancement

#18 🔀 :: 카카오 포트 추가
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/KakaoDuplicateCheckUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/KakaoSignupUseCase.kt
Labels: enhancement

#19 🔀 :: 로그인 Port 구현
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/exception/UserNotFoundException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoLoginService.kt
Labels: enhancement

#24 🔀 :: ExistsUserByOAuthId
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/UserPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/repository/UserRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/ExistUserByOAuthIdPort.kt
Labels: enhancement

#27 🔀 :: Change Login Logic
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/entity/UserJpaEntity.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/KakaoDuplicateCheckUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoLoginService.kt
Labels: enhancement

#28 🔀 :: ma-66 to develop
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/ParseAppleTokenPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/AppleLoginService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/adapter/AppleAuthAdapter.kt
Labels: documentation

#30 🔀 :: ma-69 to develop
  build.gradle.kts
  buildSrc/src/main/kotlin/PluginVersions.kt
  maeumgagym-application/build.gradle.kts
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/repository/CustomUserRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/repository/CustomUserRepositoryImpl.kt
  maeumgagym-infrastructure/build.gradle.kts
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/querydsl/QueryDslConfig.kt
Labels: enhancement

#34 🔀 :: ma-70 to devleop
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/entity/PoseJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/mapper/PoseMapper.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/Pose.kt
Labels: enhancement

#35 🔀 :: 루틴 엔티티 설계
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/base/BaseEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/base/BaseTimeEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routin/entity/ExerciseInfo.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routin/entity/RoutineJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routin/entity/RoutineStatus.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routin/mapper/RoutineMapper.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/ExerciseInfoModel.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/Routine.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/RoutineStatusModel.kt
Labels: enhancement

#36 🔀 :: ma-81 to develop
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/PosePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/entity/PoseJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/mapper/PoseMapper.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/repository/PoseRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/dto/response/PoseDetailResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/exception/PoseNotFoundException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/model/Pose.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/in/ReadByIdUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/out/FindPoseByUUIDPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/service/ReadPoseService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/AppleAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/GeneratePublicKeyAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/GoogleAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/KakaoAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/ReadCurrentUserAdapter.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/auth/controller/KakaoAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/auth/dto/request/KakaoSignupRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/pose/controller/PoseController.kt
Labels: enhancement

#40 🔀 :: Routine 생성 API
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/RoutinePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/entity/ExerciseInfo.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/entity/RoutineJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/entity/RoutineStatus.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/mapper/RoutineMapper.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/repository/RoutineRepository.kt
  maeumgagym-common/build.gradle.kts
  maeumgagym-common/src/main/kotlin/com/info/common/WebAdapter.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/request/CreateRoutineRequest.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/CreateRoutineUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/out/SaveRoutinePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CreateRoutineService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/principle/CustomUserDetailService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/routine/controller/RoutineController.kt
Labels: enhancement

#43 🔀 :: Routine Entity 수정
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/entity/RoutineJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/mapper/RoutineMapper.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/Routine.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CreateRoutineService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/ReadCurrentUserAdapter.kt
Labels: enhancement

#44 🔀 :: 내 루틴 조회 API
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/RoutinePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/repository/RoutineRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/ExerciseInfoDto.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/RoutineStatusDto.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/response/RoutineListResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/response/RoutineResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/ReadAllMyRoutineUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/out/ReadAllRoutineByUserIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/ReadAllMyAllMyRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/dto/response/UserResponse.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/routine/controller/RoutineController.kt
Labels: enhancement

#42 🔀 :: ma-85 to devlop
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/converter/StringAttributeConverter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PicklePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleLikeJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/mapper/PickleMapper.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleCommentRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleLikeRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleReplyRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/dto/request/PickleUploadRequest.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/model/Pickle.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/model/PickleLike.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/PickleUploadUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/SavePicklePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/PickleUploadService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AppleAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/GoogleOAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/KakaoAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/dto/request/KakaoSignupRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pose/PoseController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
Labels: enhancement

#45 ⭐️ :: 피클 삭제
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PicklePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleLikeRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/RoutinePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/converter/RoleConverter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/exception/UserNotFoundException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/exception/PermissionDeniedException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/GoogleOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoLoginService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoSignupService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/exception/PickleNotFoundException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/PickleDeleteUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/DeletePicklePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/ReadPickleByIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/PickleDeleteService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/exception/DuplicatedNicknameException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/exception/RoleConverterException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/exception/UserNotFoundException.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/principle/CustomUserDetailService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleController.kt
Labels: enhancement

#46 ⭐️ :: 피클 수정
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/dto/request/UpdatePickleRequest.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/UpdatePickleUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/UpdatePickleService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleController.kt
Labels: enhancement

#47 ⭐️ :: 피클 업로드 url
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/dto/request/PreSignedUploadURLRequest.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/dto/response/PreSignedUploadURLResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/exception/FileTypeMissMatchedException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/GetPreSignedUploadURLUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/GetPreSignedURLPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/GetPreSignedURLService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/file/FileAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/feign/file/FileClient.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/feign/file/dto/FilePreSignedUploadURLResponse.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/env/file/FileProperty.kt
  maeumgagym-infrastructure/src/main/resources/application.yml
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleController.kt
Labels: enhancement

#53 🔀 :: Swagger 설정
  buildSrc/src/main/kotlin/Dependencies.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/DeletePickleService.kt
  maeumgagym-infrastructure/build.gradle.kts
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/swagger/SwaggerConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/SecurityConfig.kt
  maeumgagym-infrastructure/src/main/resources/application.yml
  maeumgagym-presentation/build.gradle.kts
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AppleAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/GoogleOAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/KakaoAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pose/PoseController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
Labels: enhancement

#58 ♻️ :: token 보안 강화, reissue 버그 수정
  .github/workflows/xquare.yml
  .xquare/config.yaml
  Dockerfile
  maeumgagym-application/build.gradle.kts
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
  maeumgagym-common/src/main/kotlin/com/info/common/WebAdapter.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/GenerateJwtPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/GetJwtBodyPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/GenerateTokenService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoLoginService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/redis/RedisConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/env/security/SecurityProperties.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/exception/InvalidTokenException.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtResolver.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/entity/AccessTokenRedisEntity.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/entity/RefreshTokenRedisEntity.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/repository/AccessTokenRepository.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/repository/RefreshTokenRepository.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/SecurityConfig.kt
  maeumgagym-infrastructure/src/main/resources/application.yml
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/GoogleOAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pose/PoseController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
Labels: bug, documentation, enhancement

#59 📝 :: 구글 토큰 만료시키기
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/RevokeGoogleTokenPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/GoogleOAuthService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/GoogleAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/feign/oauth/google/GoogleAuthClient.kt
Labels: documentation, enhancement

#60 🔀 :: 루틴 삭제 API
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/RoutinePersistenceAdapter.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/exception/RoutineNotFoundException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/DeleteRoutineUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/out/DeleteRoutinePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/out/ReadRoutineByIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/DeleteRoutineService.kt
  maeumgagym-infrastructure/build.gradle.kts
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/quote/QuoteTests.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/quote/exception/MismatchQuoteAndQuoterException.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/RoutineTests.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
Labels: enhancement

#62 🔀 :: 루틴 PK 타입 Long으로 변경
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/RoutinePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/entity/RoutineJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/repository/RoutineRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/response/RoutineResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/Routine.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/DeleteRoutineUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/out/ReadRoutineByIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/DeleteRoutineService.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/RoutineTests.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/RoutineWebResponse.kt
Labels: enhancement

#63 🔀 :: 루틴 수정 API
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/request/UpdateRoutineRequest.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/UpdateRoutineUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/UpdateRoutineService.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/DeleteRoutineServiceTests.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/UpdateRoutineServiceTests.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/request/CreateRoutineWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/request/UpdateRoutineWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/response/RoutineWebListResponse.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/response/RoutineWebResponse.kt
Labels: enhancement
