Repository MaeumGaGym/MaeumGaGym_Backend, pull requests merged in 2024-03, with the labels that each got.

#142 ✨ :: Daily 생성, 수정, 보기, 삭제 API
  .github/workflows/run-test-code.yml
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/daily/DailyPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/daily/entity/DailyJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/daily/mapper/DailyMapper.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/daily/repository/DailyRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/dto/response/DailyListResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/dto/response/DailyResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/dto/response/PreSignedURLResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/exception/DailyNotFoundException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/exception/ThereNoDailiesException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/model/Daily.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/model/FileTypes.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/port/in/CreateDailyUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/port/in/DeleteDailyUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/port/in/GetDailyPreSignedURLUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/port/in/ReadDailyUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/port/in/UpdateDailyUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/port/out/DeleteDailyPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/port/out/DeleteImageObjectPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/port/out/GetPreSignedImageUploadURL.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/port/out/ReadDailyPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/port/out/SaveDailyPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/service/CreateDailyService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/service/DeleteDailyService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/service/GetDailyDailyPreSignedURLService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/service/ReadDailyService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/service/UpdateDailyService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/GetPicklePreSignedURLUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/GetPicklePreSignedURLService.kt
  maeumgagym-infrastructure/build.gradle.kts
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/file/FileAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/file/MinIOAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/feign/file/FileClient.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/minio/MinIOConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/env/file/MinIOProperties.kt
  maeumgagym-infrastructure/src/main/resources/application-minio.yml
  maeumgagym-infrastructure/src/main/resources/application.yml
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/daily/DailyController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/daily/dto/CreateDailyRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/daily/dto/DailyTitleUpdateRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleController.kt
Labels: 기능 추가

#143 📝 :: CSRF Temporary disuse
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/security/SecurityConfig.kt
Labels: 리펙토링

#150 📝 :: Location Header를 작성하는 Interceptor 추가
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/dto/LocationSubjectDto.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/port/in/CreateDailyUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/daily/service/CreateDailyService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/CreatePickleCommentUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/CreatePickleReplyCommentUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/CreatePickleUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleCommentService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleReplyCommentService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/port/in/CreatePurposeUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/service/CreatePurposeService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/CreateRoutineUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CreateRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/service/UpdateUserInfoService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/interceptor/InterceptorChainConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/locationheader/LocationHeaderInterceptor.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/locationheader/SimpleLocationHeaderManager.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/common/locationheader/LocationHeaderSubjectManager.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/daily/DailyController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleReplyController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/purpose/PurposeController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
Labels: 기능 추가

#151 📝 :: 자세 Entity 재설계
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/entity/PoseJpaEntity.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/dto/response/PoseDetailResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/model/Pose.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/pose/PoseTestModule.kt
Labels: 리펙토링

#152 ✨ :: RoutineHistory 생성 API
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/RoutineHistoryPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/RoutinePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/entity/RoutineHistoryJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/mapper/RoutineHistoryMapper.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/mapper/RoutineMapper.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/repository/RoutineHistoryRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/repository/RoutineNativeRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/Exceptions.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/response/RoutineResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/Routine.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/RoutineHistory.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/CompleteTodayRoutineUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/out/ExistsRoutineHistoryPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/out/ReadRoutineHistoryPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/out/ReadRoutinePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/out/SaveRoutineHistoryPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CompleteTodayRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/ReadTodayRoutineService.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/ReadRoutineServiceTests.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
Labels: 기능 추가

#154 📝 :: 자세 태그 기반 검색
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/PosePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/repository/PoseNativeRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/dto/response/PoseInfoResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/dto/response/PoseListResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/model/Pose.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/in/ReadPoseFromIdUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/in/ReadPoseFromTagUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/out/ReadPosePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/service/ReadPoseFromIdService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/service/ReadPoseFromTagService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pose/PoseController.kt
Labels: 기능 추가

#155 📝 :: Logout 로직을 LogoutFilter로 이전
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/LogOutUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/LogOutService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/handler/CustomLogoutHandler.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/handler/CustomSuccessLogoutHandler.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/LogoutHandlerConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/SecurityConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/SecurityFilterChainConfig.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AuthController.kt
Labels: 리펙토링

#156 📝 :: ErrorLogResponseFilter에서의 성공 응답에 대한 추가적인 처리 및 ResponseWriter 추가
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/CustomAccessDeniedHandler.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/CustomAuthenticationEntryPoint.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/filter/ErrorLogResponseFilter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/filter/FilterChainConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/interceptor/InterceptorChainConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/response/locationheader/LocationHeaderInterceptor.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/response/locationheader/SimpleLocationHeaderManager.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/response/writer/DefaultHttpServletResponseWriter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/response/writer/ErrorLogHttpServletResponseWriter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/response/writer/HttpServletResponseWriter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/response/writer/impl/DefaultHttpServletResponseWriterImpl.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/response/writer/impl/ErrorLogHttpServletResponseWriterImpl.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/SecurityFilterChainConfig.kt
Labels: 버그, 리펙토링, 기능 추가

#164 delete
  .github/workflows/add-label-on-comment.yaml
Labels: lgtm

#173 delete unused workflow file
  .github/workflows/comment-on-task.yaml
Labels: kind/리펙토링, lgtm, size/S

#174 PR :: Location Header 혹은 Body를 작성하지 않는 API에서 204 상태 코드 반환
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/response/locationheader/LocationHeaderInterceptor.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AppleAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/GoogleOAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/daily/DailyController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleReplyController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/purpose/PurposeController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/step/StepController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/user/UserController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/wakatime/WakatimeController.kt
Labels: kind/리펙토링, lgtm, size/M

#175 PR :: infrastructure 패키지 구조 변경
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/in/UpdateUserInfoUseCase.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/oauth/AppleAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/oauth/GoogleAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/oauth/KakaoAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/config/scan/PropertiesScanConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/filter/ErrorLogResponseFilter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/filter/ExceptionConvertFilter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/handler/CustomAccessDeniedHandler.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/handler/CustomAuthenticationEntryPoint.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/vo/ErrorLog.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/vo/ErrorResponse.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/external/feign/oauth/apple/AppleClient.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/external/feign/oauth/apple/dto/ApplePublicKeyFeignResponse.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/external/feign/oauth/apple/dto/ApplePublicKeysFeignResponse.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/external/feign/oauth/google/GoogleAuthClient.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/external/feign/oauth/google/GoogleInfoClient.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/external/feign/oauth/google/dto/GoogleInfoFeignResponse.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/external/feign/oauth/kakao/KakaoInfoClient.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/external/feign/oauth/kakao/dto/KakaoInfoFeignResponse.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/external/feign/oauth/kakao/dto/PropertiesFeignResponse.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/response/writer/ErrorLogHttpServletResponseWriter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/response/writer/impl/ErrorLogHttpServletResponseWriterImpl.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/scheduler/config/SchedulerConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/LogoutHandlerConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/RequestPermitConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/SecurityConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/SecurityLogConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/cors/CorsConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/env/CSRFProperties.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/env/SecurityProperties.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/jwt/JwtAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/jwt/JwtResolver.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/jwt/env/JwtProperties.kt
Labels: kind/리펙토링, lgtm, size/M

#176 PR :: Delete run-test-code file
  .github/workflows/run-test-code.yml
Labels: kind/리펙토링, lgtm, size/M

#177 PR :: GoogleInfoResponse에서 locale 제거
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/dto/response/GoogleInfoResponse.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/external/feign/oauth/google/dto/GoogleInfoFeignResponse.kt
Labels: kind/버그, lgtm, size/XS

#179 PR :: discord notification yml Enchant
  .github/workflows/discord-notification.yml
Labels: kind/리펙토링, kind/기능, lgtm, size/XS, kind/문서

#178 PR :: 싱글톤 Exception들을 생성 방식으로 수정
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/Exceptions.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/error/TestException.kt
Labels: kind/버그, lgtm, size/M

#182 PR :: Authentication에서 UserDetails 제거
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/ReadCurrentUserAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/RequestPermitConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/jwt/JwtFilter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/jwt/impl/AuthenticationProviderImpl.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/principle/CustomUserDetailService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/principle/CustomUserDetails.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/auth/AuthTestModule.kt
Labels: kind/리펙토링, lgtm, size/L

#183 PR :: 와카타임 총 시간(s) 조회 API
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/dto/response/WakatimeResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/port/in/ReadWakaTimeUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/service/ReadWakatimeService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/wakatime/WakatimeController.kt
Labels: kind/기능, lgtm, size/M

#184 PR :: Exception 관련 필터를 SecurityFilterChain에서 분리
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/config/filter/FilterChainConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/filter/ErrorLogResponseFilter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/filter/ExceptionConvertFilter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/filter/filterchain/ExceptionChainedFilterChain.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/filter/filterchain/ExceptionChainedFilterChainProxy.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/chained/ChainedFilterChain.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/chained/ChainedFilterChainProxy.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/config/ApplicationFilterChainConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/config/SecurityFilterChainConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/global/GlobalFilterChain.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/global/GlobalFilterChainProxy.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/SecurityConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/jwt/JwtFilter.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/auth/JwtTests.kt
Labels: kind/리펙토링, kind/기능, size/L

#185 PR :: FilterChain 리펙토링
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/filter/filterchain/ExceptionChainedFilterChain.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/filter/filterchain/ExceptionChainedFilterChainProxy.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/chained/ChainedFilterChain.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/global/GlobalFilterChain.kt
Labels: kind/버그, kind/리펙토링, lgtm, approved, size/M
