Repository MaeumGaGym/MaeumGaGym_Backend, pull requests merged in 2024-02, with the labels that each got.

#124 📝 :: 피클 테스트 코드 작성
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/mapper/PickleMapper.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/pickle/CreatePickleServiceTests.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/pickle/LoadPickleServiceTests.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/pickle/PickleTestModule.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/pickle/UpdatePickleServiceTests.kt
Labels: 리펙토링

#126 📝:: 오늘의 루틴 조회 기능 구현
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/response/RoutineResponseWrapper.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/Routine.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/ReadTodayRoutineUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/ReadMyAllRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/ReadTodayRoutineService.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/ReadRoutineServiceTests.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/RoutineTestModule.kt
Labels: 기능 추가

#127 ✨ :: 걸음수 생성, 수정 API 구현
  maeumgagym-application/build.gradle.kts
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/step/StepPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/step/entity/StepRedisEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/step/mapper/StepMapper.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/step/repository/StepRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/step/exception/AlreadyExistStepException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/step/exception/StepNotFoundException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/step/model/Step.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/step/port/in/CreateStepUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/step/port/in/UpdateStepUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/step/port/out/ReadStepPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/step/port/out/SaveStepPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/step/service/CreateStepService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/step/service/UpdateStepService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/step/StepController.kt
Labels: 기능 추가

#128 📝 :: 오늘의 루틴 컨트롤러 추가 및 없을 시 204 반환
  maeumgagym-common/src/main/kotlin/com/info/common/UseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/response/RoutineResponseWrapper.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/ReadTodayRoutineUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/ReadTodayRoutineService.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/ReadRoutineServiceTests.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/RoutineTestModule.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
Labels: 버그, 기능 추가

#131 📝 :: SecurityConfig 분리 및 Filter 등 빈 등록
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/MaeumGaGymApplication.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/filter/MaeumGaGymExceptionFilter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/scan/PropertiesScanConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/security/CorsConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/security/RequestPermitConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/security/SecurityConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/security/SecurityFilterChainConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/CustomAccessDeniedHandler.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/CustomAuthenticationEntryPoint.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/ErrorResponse.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/MaeumGaGymExceptionHandler.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtFilter.kt
Labels: 리펙토링

#132 📝 :: 목표 추가 구현
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/purpose/PurposePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/purpose/entity/PurposeJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/purpose/mapper/PurposeMapper.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/purpose/repository/PurposeRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/convertor/LocalDateConvertor.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/dto/request/CreatePurposeRequest.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/exception/StartDateCannotAfterThanEndDateException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/model/Purpose.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/port/in/CreatePurposeUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/port/out/SavePurposePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/service/CreatePurposeService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/filter/MaeumGaGymExceptionFilter.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/purpose/PurposeController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/purpose/dto/CreatePurposeWebRequest.kt
Labels: 기능 추가

#133 📝 :: 목표 수정 API 구현
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/purpose/PurposePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/purpose/repository/PurposeRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/convertor/LocalDateConvertor.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/dto/request/UpdatePurposeRequest.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/exception/PurposeNotFoundException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/port/in/UpdatePurposeUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/port/out/ReadPurposePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/service/UpdatePurposeService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/purpose/PurposeController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/purpose/dto/UpdatePurposeWebRequest.kt
Labels: 기능 추가

#138 ✨ :: delete purpose API
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/purpose/PurposePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/purpose/repository/PurposeRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/port/in/DeletePurposeUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/port/in/UpdatePurposeUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/port/out/DeletePurposePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/service/DeletePurposeService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/service/UpdatePurposeService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/purpose/PurposeController.kt
Labels: 리펙토링, 기능 추가

#139 ✨ :: 프로필 보기 API
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/in/ReadPoseUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/service/ReadPoseService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/dto/response/UserProfileResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/in/ReadUserUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/service/ReadUserService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/util/WakatimeUtils.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pose/PoseController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/statistics/PublicController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/user/UserController.kt
Labels: 기능 추가
