Repository MaeumGaGym/MaeumGaGym_Backend, pull requests merged in 2024-04, with the labels that each got.

#188 PR :: 자세 추천 기능 추가
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/PosePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/repository/PoseNativeRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/dto/response/PoseRecommendationListResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/model/Pose.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/in/ReadPosesRecommendationUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/out/ReadPosePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/service/ReadPosesRecommendationService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pose/PoseController.kt
Labels: kind/기능

#189 PR :: Routine 속의 Pose를 id로 저장
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/entity/ExerciseInfo.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/mapper/RoutineHistoryMapper.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/mapper/RoutineMapper.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/ExerciseInfoDto.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/request/CreateRoutineRequest.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/request/ExerciseInfoRequest.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/request/UpdateRoutineRequest.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/response/ExerciseInfoResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/response/RoutineHistoryResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/response/RoutineResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/ExerciseInfoModel.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/Routine.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/RoutineHistory.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CreateRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/UpdateRoutineService.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/RoutineTestModule.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/CreateRoutineWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/UpdateRoutineWebRequest.kt
Labels: kind/기능

#191 PR :: AuthenticationProvider 리팩토링
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/ReadCurrentUserAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/config/SecurityFilterChainConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/authentication/AuthenticationProvider.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/authentication/UserModelAuthenticationProvider.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/authentication/UsernamePasswordAuthenticationTokenProvider.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/authentication/impl/UserModelAuthenticationProviderImpl.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/authentication/impl/UsernamePasswordAuthenticationTokenProviderImpl.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/authentication/vo/UserModelAuthentication.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/jwt/AuthenticationProvider.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/jwt/JwtFilter.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/auth/JwtTests.kt
Labels: kind/기능

#192 PR :: 카카오 로그인 V2 만들기
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/dto/response/KakaoProfileResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/GetKakaoInfoPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/GetKakaoProfilePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/GetKakaoTokenPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/KakaoGenerateTokenUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/RevokeKakaoTokenPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoOAuthService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/oauth/KakaoAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/env/feign/KakaoProperties.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/external/feign/oauth/kakao/KakaoApiClient.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/external/feign/oauth/kakao/KakaoAuthClient.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/external/feign/oauth/kakao/dto/KakaoAuthResponse.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/external/feign/oauth/kakao/dto/KakaoProfileFeignResponse.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/RequestPermitConfig.kt
  maeumgagym-infrastructure/src/main/resources/application-kakao.yml
  maeumgagym-infrastructure/src/main/resources/application.yml
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/KakaoAuthController.kt
Labels: kind/기능, size/M

#195 PR :: UserModelAuthentication을 이용한 인가 방식으로 수정
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/ReadCurrentUserAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/config/ApplicationFilterChainConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/config/SecurityFilterChainConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/authentication/AuthenticationProvider.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/authentication/UsernamePasswordAuthenticationTokenProvider.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/authentication/impl/UserModelAuthenticationProviderImpl.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/authentication/impl/UsernamePasswordAuthenticationTokenProviderImpl.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/authentication/vo/UserModelAuthentication.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/jwt/JwtFilter.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/auth/JwtTests.kt
Labels: kind/리펙토링

#194 PR :: ErrorLog 포맷 수정 및 보안 향상
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/vo/ErrorLog.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/response/writer/ErrorLogHttpServletResponseWriter.kt
Labels: kind/리펙토링, 보안 향상

#197 PR :: Custom 어노테이션 기반의 Role 인증 구현
  maeumgagym-common/src/main/kotlin/com/info/common/security/RequireRole.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/Exceptions.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/collection/AnnotationBeanCollection.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/collection/BeanCollection.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/collection/impl/AnnotationBeanCollectionImpl.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/config/interceptor/InterceptorChainConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/response/locationheader/LocationHeaderInterceptor.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/authentication/interceptor/RoleAuthenticationInterceptor.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/RequestPermitConfig.kt
Labels: kind/리펙토링, kind/기능, do-not-merge/hold

#199 PR :: Request의 요일 정보를 한글로 입력
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/convertor/DayOfWeekConvertor.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CreateRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/UpdateRoutineService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/CreateRoutineWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/UpdateRoutineWebRequest.kt
Labels: kind/리펙토링, kind/기능

#200 PR :: Refact day_of_weeks
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/Routine.kt
Labels: kind/리펙토링, lgtm, size/S

#207 PR ::요일 입력 시 "요일" 단위 생략 가능하도록 수정
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/convertor/DayOfWeekConvertor.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CreateRoutineService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/CreateRoutineWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/UpdateRoutineWebRequest.kt
Labels: kind/버그, kind/기능, lgtm, approved, size/M

#208 PR :: 내 목표 조회 API 구현
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/purpose/PurposePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/purpose/repository/PurposeRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/RoutinePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/repository/current/RoutineRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/port/in/ReadAllMyPurposeUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/port/out/ReadPurposePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/ReadAllMyRoutineUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/out/ReadRoutinePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/ReadAllMyPurposeService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/ReadMyAllRoutineService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/purpose/PurposeController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
Labels: kind/리펙토링, kind/기능, lgtm, approved, size/M

#209 PR :: 인증 관련 커스텀 어노테이션 추가 및 관련 로직 구현
  maeumgagym-common/src/main/kotlin/com/info/common/security/Permitted.kt
  maeumgagym-common/src/main/kotlin/com/info/common/security/RequireAuthentication.kt
  maeumgagym-common/src/main/kotlin/com/info/common/security/RequireRole.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/collection/annotation/AnnotationCollection.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/collection/annotation/AnnotationCollectionComposite.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/collection/annotation/DefaultAnnotationCollection.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/collection/annotation/HandlerAnnotationCollection.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/config/argresolver/HandlerMethodArgumentResolverConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/config/interceptor/InterceptorChainConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/access/checker/AbstractAnnotationBasedUserAuthenticationChecker.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/access/checker/AnnotationBasedUserAuthenticationChecker.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/access/checker/composite/AnnotationBasedUserAuthenticationCheckerComposite.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/access/checker/impl/RequireAuthenticationChecker.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/access/checker/impl/RequireRoleChecker.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/access/interceptor/AccessManagerDelegateInterceptor.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/access/manager/AccessManager.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/access/manager/AccessManagerImpl.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/authentication/interceptor/RoleAuthenticationInterceptor.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/authentication/resolver/AuthenticationHandlerMethodArgumentResolver.kt
Labels: kind/리펙토링, kind/기능, lgtm, approved, size/XL

#210 PR :: Infrastructure 계층 문서화
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/GenerateJwtPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/ReissuePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/RevokeTokensPort.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/filter/ErrorLogResponseFilter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/filter/ExceptionConvertFilter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/filter/filterchain/ExceptionChainedFilterChain.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/filter/filterchain/ExceptionChainedFilterChainProxy.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/repository/ExceptionRepository.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/chained/ChainedFilterChain.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/chained/ChainedFilterChainProxy.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/config/ApplicationFilterChainConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/config/SecurityFilterChainConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/global/GlobalFilterChain.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/global/GlobalFilterChainProxy.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/response/locationheader/LocationHeaderInterceptor.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/response/writer/ErrorLogHttpServletResponseWriter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/authentication/UserModelAuthenticationProvider.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/LogoutHandlerConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/RequestPermitConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/SecurityConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/SecurityLogConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/config/cors/CorsConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/handler/CustomLogoutHandler.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/handler/CustomSuccessLogoutHandler.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/jwt/JwtFilter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/jwt/impl/JwtAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/jwt/repository/AccessTokenRepository.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/security/jwt/repository/RefreshTokenRepository.kt
Labels: lgtm, approved, size/L, kind/문서

#211 PR :: Collector 리팩토링
  src/main/kotlin/com/info/maeumgagym/infrastructure/collector/OWNERS
  src/main/kotlin/com/info/maeumgagym/infrastructure/collector/annotation/AnnotationCollector.kt
  src/main/kotlin/com/info/maeumgagym/infrastructure/collector/annotation/AnnotationCollectorComposite.kt
  src/main/kotlin/com/info/maeumgagym/infrastructure/collector/annotation/DefaultAnnotationCollector.kt
  src/main/kotlin/com/info/maeumgagym/infrastructure/collector/annotation/HandlerAnnotationCollector.kt
  src/main/kotlin/com/info/maeumgagym/infrastructure/collector/bean/AnnotationBasedBeanCollector.kt
  src/main/kotlin/com/info/maeumgagym/infrastructure/collector/bean/BeanCollector.kt
  src/main/kotlin/com/info/maeumgagym/infrastructure/collector/bean/impl/AnnotationBasedBeanCollectorImpl.kt
  src/main/kotlin/com/info/maeumgagym/security/access/checker/impl/RequireAuthenticationChecker.kt
  src/main/kotlin/com/info/maeumgagym/security/access/checker/impl/RequireRoleChecker.kt
Labels: kind/리펙토링, lgtm, approved, size/M
