Repository MaeumGaGym/MaeumGaGym_Backend, pull requests merged in 2024-01, with the labels that each got.

#66 ⭐️ :: 회원 복구, 30일 지난 유저 약정에 따라 자동 하드 딜리트
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/DeletedAtPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/UserPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/entity/DeleteAtJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/entity/DeletedUserJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/mapper/UserMapper.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/repository/DeletedAtRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/repository/DeletedUserRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/repository/UserRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/AppleLoginUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/AppleRecoveryUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/AppleSignUpUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/GoogleRecoveryUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/KakaoRecoveryUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/DeleteDeletedAtPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/AppleLoginService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/AppleOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/AppleRecoveryService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/DuplicatedCheckService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/GenerateTokenService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/GoogleOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoLoginService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoSignupService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/WithdrawalUserService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/model/DeleteAt.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/model/DeletedUser.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/ExistUserByNicknamePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/ExistUserByOAuthIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/ExistsDeletedUserByIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/FindDeletedAtByIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/FindDeletedUserByIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/RecoveryUserPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/SaveDeletedAtPort.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/MaeumGaGymApplication.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/RecoveryAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/scheduler/SchedulerConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/SecurityConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/scheduler/UserScheduler.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AppleAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/GoogleOAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/KakaoAuthController.kt
Labels: bug, documentation, enhancement

#67 ♻️ :: refactoring & comments
  maeumgagym-application/build.gradle.kts
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/AppleOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/GoogleOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/WithdrawalUserService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/DeletePickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/GetPreSignedURLService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/LoadPickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/UploadPickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/DeleteRoutineUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/DeleteRoutineService.kt
  maeumgagym-infrastructure/build.gradle.kts
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/AppleAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/GeneratePublicKeyAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/GoogleAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/KakaoAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/ReadCurrentUserAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/RecoveryAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/scheduler/SchedulerConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/AppleJwtParser.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtFilter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtResolver.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/principle/CustomUserDetailService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/scheduler/UserScheduler.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AppleAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/GoogleOAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/KakaoAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pose/PoseController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
Labels: bug, documentation, duplicate

#71 ♻️ :: refactoring & comments
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/dto/response/PreSignedUploadURLResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/GetPreSignedUploadURLUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/UpdatePickleUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/GetPreSignedURLService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/UpdatePickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/service/ReadPoseService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/UpdateRoutineUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CreateRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/DeleteRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/ReadMyAllRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/UpdateRoutineService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AppleAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/GoogleOAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/KakaoAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/dto/KakaoSignupWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/dto/ReissueWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/dto/SignupWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/dto/response/TokenWebResponse.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/dto/PickleUploadWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/dto/PreSignedUploadURLWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/dto/UpdatePickleWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/dto/response/PickleWebResponse.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/dto/response/PreSignedUploadURLWebResponse.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/quote/QuoteController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/quote/dto/response/QuoteWebResponse.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/CreateRoutineWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/UpdateRoutineWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/response/RoutineWebListResponse.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/response/RoutineWebResponse.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/user/dto/UserWebResponse.kt
Labels: documentation, duplicate

#78 🔀 :: 피클 댓글 생성 기능
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PickleCommentPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PicklePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleCommentJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleReplyJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/mapper/PickleCommentMapper.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleReplyRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/dto/request/PickleCommentRequest.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/exception/PickleCommentNotFoundException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/exception/PickleMisMatchException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/model/PickleComment.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/CreatePickleCommentUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/CreatePickleReplyCommentUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/ExistsPickleByIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/ReadPickleCommentPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/SavePickleCommentPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleCommentService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleReplyCommentService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtAdapter.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/dto/PickleCommentWebRequest.kt
Labels: enhancement

#84 📝 :: 회원 가입시 토큰 만료되도록 변경
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PicklePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/DeletedAtPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/UserPersistenceAdapter.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/RevokeTokensPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/AppleOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/GenerateTokenService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/GoogleOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/WithdrawalUserService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtAdapter.kt
Labels: enhancement

#88 ✨ :: Release Auto Create
  .github/workflows/release-auto.yml
Labels: enhancement

#91 ✨ :: 와카타임 시작, 종료 구현
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/entity/UserJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/mapper/UserMapper.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/repository/UserRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/wakatime/WakaTimePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/wakatime/entity/WakaTimeJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/wakatime/mapper/WakaTimeMapper.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/wakatime/repository/WakaTimeRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/model/User.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/exception/AlreadyWakaStartedException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/exception/WakaStartedNotYetException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/model/WakaTime.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/port/in/EndWakatimeUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/port/in/StartWakatimeUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/port/out/ReadWakaTimeFromUserAndDatePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/port/out/SaveWakaTimePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/service/EndWakatimeService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/service/StartWakatimeService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/scheduler/SchedulerConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/scheduler/UserScheduler.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/user/module/UserTestModule.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/wakatime/WakatimeController.kt
Labels: enhancement

#93 ⚡️ :: update or insert 쿼리 성능
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/wakatime/entity/WakaTimeJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/wakatime/mapper/WakaTimeMapper.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/model/WakaTime.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/service/EndWakatimeService.kt
Labels: documentation

#95 📝 :: 접근 제한자 추가
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/converter/StringAttributeConverter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PickleCommentPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PicklePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/PosePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/RoutinePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/DeletedAtPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/UserPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/converter/RoleConverter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/wakatime/WakaTimePersistenceAdapter.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/AppleOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/DuplicatedCheckService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/GoogleOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/ReissueService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/WithdrawalUserService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleCommentService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleReplyCommentService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/DeletePickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/GetPreSignedURLService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/LoadPickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/UpdatePickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/UploadPickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/service/ReadPoseService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/quote/service/ReadRandomQuoteService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CreateRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/DeleteRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/ReadMyAllRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/UpdateRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/service/EndWakatimeService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/service/StartWakatimeService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/AppleAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/GeneratePublicKeyAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/GoogleAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/KakaoAuthAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/ReadCurrentUserAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/RecoveryAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/file/FileAdapter.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/auth/junit5/DuplicatedCheckServiceTests.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/quote/junit5/QuoteTests.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/junit5/ReadRoutineServiceTests.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/kotest/DeleteRoutineServiceTestsWithKotest.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/kotest/UpdateRoutineServiceTestsWithKotest.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/user/junit5/ReadCurrentUserAdapterTests.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/user/junit5/WithdrawalUserServiceTests.kt
Labels: documentation

#97 ⚡️ :: exists, native query
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PicklePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleReplyRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/UserPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/repository/UserRepository.kt
Labels: enhancement

#101 📝 :: native query Repository 분할
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PickleCommentPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PicklePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PickleReplyPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleCommentMappedRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleCommentRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleLikeRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleReplyRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/PosePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/repository/PoseRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/RoutinePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/repository/RoutineRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/DeletedAtPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/UserPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/repository/DeletedAtRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/repository/UserNativeRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/repository/UserRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/wakatime/WakaTimePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/wakatime/repository/WakaTimeRepository.kt
  maeumgagym-common/src/main/kotlin/com/info/common/UseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/DeleteDeletedAtPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/AppleOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/DuplicatedCheckService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/GoogleOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/ReissueService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/WithdrawalUserService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleCommentService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleReplyCommentService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/DeletePickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/UpdatePickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/UploadPickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CreateRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/DeleteRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/UpdateRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/ExistUserByNicknamePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/ExistUserByOAuthIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/FindDeletedAtByIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/FindDeletedUserByIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/service/EndWakatimeService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/service/StartWakatimeService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/RecoveryAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/scheduler/UserScheduler.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/scheduler/WakaTimeScheduler.kt
  maeumgagym-infrastructure/src/main/resources/application.yml
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/DeleteRoutineServiceTests.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/UpdateRoutineServiceTests.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/user/WithdrawalUserServiceTests.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/wakatime/WakatimeTests.kt
Labels: documentation

#102 ✨ :: 댓글 조회 Paging 처리
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PickleCommentPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleCommentRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/ReadAllPagedPickleCommentUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/ReadAllPickleCommentsUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/ReadAllPagedPickleCommentsByVideoIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/ReadAllPickleCommentsByVideoIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/ReadAllPagedPickleCommentService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/GlobalExceptionHandler.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
Labels: documentation

#105 ✨ :: 피클 대댓글 조회 페이징 처리
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PickleReplyPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleReplyRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/LoadAllPickleReplyUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/ReadAllReplyByParentCommentPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/ReadAllPickleReplyService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleReplyController.kt
Labels: 기능 추가

#107 ✨ :: 피클 댓글 삭제 기능
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PickleCommentPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleCommentRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/DeletePickleCommentUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/DeletePickleCommentPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/ReadPickleCommentPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleReplyCommentService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/DeletePickleCommentService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/ReadAllPickleReplyService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
Labels: 기능 추가

#109 📝 :: 신고 기능 구현
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PickleReplyPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleReplyRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/report/ReportPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/report/entity/ReportJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/report/mapper/ReportMapper.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/report/repository/ReportRepository.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/UserPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/repository/UserRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/exception/PickleReplyNotFoundException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/ReadPickleReplyPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/report/dto/request/ReportRequest.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/report/exception/CannotReportOneselfException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/report/model/Report.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/report/model/ReportStatus.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/report/model/ReportType.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/report/port/in/ReportPickleCommentUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/report/port/in/ReportPickleReplyUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/report/port/in/ReportPickleUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/report/port/in/ReportUserUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/report/port/out/SaveReportPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/report/service/ReportService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/ReadUserByNicknamePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/ReadUserPort.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/SecurityConfig.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/report/ReportController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/report/dto/ReportWebRequest.kt
Labels: 기능 추가

#110 🔐 :: CSRF, XSS 공격 방어
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/dto/response/TokenResponse.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/AppleLoginUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/GoogleLoginUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/KakaoLoginUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/ReissueUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/GenerateJwtPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/ReissuePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/AppleOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/GoogleOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoOAuthService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/ReissueService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/file/FileAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/env/file/FileProperties.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/FilterConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/SecurityConfig.kt
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/auth/JwtTests.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AppleAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/GoogleOAuthController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/KakaoAuthController.kt
Labels: 보안 향상

#111 ✨ :: 피클 대댓글 삭제 기능
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PickleReplyPersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleReplyRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/CreatePickleUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/DeletePickleCommentUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/DeletePickleReplyUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/DeletePickleUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/PickleDeleteUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/DeletePickleReplyPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/DeletePickleCommentService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/DeletePickleReplyService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/DeletePickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/UploadCreatePickleService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleReplyController.kt
Labels: 기능 추가

#112 ✨ :: Deploy Workflow 추가
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stag.yml
Labels: 기능 추가

#113 📝 :: PreSignedURL과 같이 오는 VideoId 저장
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stag.yml
  .github/workflows/run-test-code.yml
  Dockerfile
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/dto/PreSignedUploadURLDto.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/exception/NotUploadedToVideoServerException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/exception/VideoAndUploaderMismatchException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/model/VideoIdAndUploaderId.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/GetPreSignedVideoUploadURLPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/ReadVideoIdAndUploaderIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/SaveVideoIdAndUploaderIdPort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/GetPreSignedURLService.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/file/FileAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/file/FileRedisPersistenceAdapter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/feign/file/dto/response/FilePreSignedUploadURLFeignResponse.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/env/file/FileProperties.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/file/VideoIdAndUploaderIdRepository.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/file/entity/VideoIdAndUploaderIdRedisEntity.kt
  maeumgagym-infrastructure/src/main/resources/application.yml
Labels: 기능 추가

#115 📝 :: refactoring
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PicklePersistenceAdapter.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleLikeJpaEntity.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/mapper/PickleMapper.kt
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleNativeRepository.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/exception/FileTypeMismatchException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/exception/PickleMismatchException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/exception/VideoAndUploaderMismatchException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/model/PickleLike.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/LoadPickleFromPoseUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/LoadPicklesFromPoseUseCase.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/ReadPicklePort.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleReplyCommentService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/GetPreSignedURLService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/LoadPickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CreateRoutineService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/ReadMyAllRoutineService.kt
  maeumgagym-infrastructure/src/main/resources/application.yml
  maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/CreateRoutineServiceTests.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleReplyController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/dto/PickleCommentWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pose/PoseController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pose/dto/PoseDetailWebResponse.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/CreateRoutineWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/UpdateRoutineWebRequest.kt
Labels: 리펙토링

#114 📝 :: 피클 문자열 필드 크기 지정
  maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleJpaEntity.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/exception/TagTooLongException.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleService.kt
  maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/UpdatePickleService.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/dto/CreatePickleWebRequest.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/dto/UpdatePickleWebRequest.kt
Labels: 리펙토링

#117 ✨ :: CSRF Token 발급용 API
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/filter/FilterConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/security/SecurityConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/CustomAccessDeniedHandler.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/CustomAuthenticationEntryPoint.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/GlobalExceptionFilter.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/GlobalExceptionHandler.kt
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/public/PublicController.kt
Labels: 리펙토링, 기능 추가

#118 ✨ :: health check API
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/security/SecurityConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/CustomAuthenticationEntryPoint.kt
  maeumgagym-infrastructure/src/main/resources/application.yml
  maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AuthController.kt
Labels: 기능 추가

#119 ♻️ :: yml 프로필로 관리하기
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stag.yml
  .github/workflows/klint-check.yml
  .github/workflows/release-auto.yml
  .github/workflows/run-test-code.yml
  Dockerfile
  build.gradle.kts
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/security/SecurityConfig.kt
  maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/env/security/SecurityProperties.kt
  maeumgagym-infrastructure/src/main/resources/application-datasource.yml
  maeumgagym-infrastructure/src/main/resources/application-file.yml
  maeumgagym-infrastructure/src/main/resources/application-jwt.yml
  maeumgagym-infrastructure/src/main/resources/application-local.yml
  maeumgagym-infrastructure/src/main/resources/application-log.yml
  maeumgagym-infrastructure/src/main/resources/application-prod.yml
  maeumgagym-infrastructure/src/main/resources/application-redis.yml
  maeumgagym-infrastructure/src/main/resources/application-stag.yml
  maeumgagym-infrastructure/src/main/resources/application-swagger.yml
  maeumgagym-infrastructure/src/main/resources/application.yml
Labels: 리펙토링

#121 🚀 :: 1.2.1 PROD
  maeumgagym-infrastructure/src/main/resources/application-prod-datasource.yml
  maeumgagym-infrastructure/src/main/resources/application-stag-datasource.yml
  maeumgagym-infrastructure/src/main/resources/application.yml
Labels: 버그, 릴리즈

#122 🚀 :: 1.2.2 PROD
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stag.yml
  maeumgagym-infrastructure/src/main/resources/application.yml
Labels: 버그, 릴리즈
